### PR TITLE
Add some Optimica related keywords

### PR DESCRIPTION
**Pull request by LJBD**
Added `optimization` and `constraint` to the keywords list and corrected the layout afterwards.

### CODE REVIEW

**Comment by dietmarw** [comment]
I'm not sure it is a good idea to add non-standard non-modelica keywords to this file. I'd rather have them in a separate `listings-optimica.cfg` file or as an alternative inside its own `morekeywords[3]` list. This would also allow to control the highlighting for those non-standard keywords. Do you think you could adjust your PR?

**Comment by LJBD** [comment]
Sure, I'll add that file instead of polluting the existing configuration.

**Comment by LJBD** [comment]
I've added new colours for the keywords - is that all right or do you prefer to keep it all blue?

**Comment by dietmarw** [comment]
Probably fine for now. We can revisit it if/when people complain. :smile: 
Thanks for the extension.

**Pull request merged**
